from aiogram.dispatcher.filters.state import StatesGroup, State

class UserState(StatesGroup):
    start_menu = State()
    thems = State()
    select_deck = State()
    allegorii = State()
    radost = State()
    strah = State()
    select_card = State()
    allegorii2 = State()
    radost2 = State()
    strah2 = State()
    allegorii3 = State()
    radost3 = State()
    strah3 = State()
    back = State()
    last_back = State()
    questi = State()
    question1 = State()
    question2 = State()
    question3 = State()
    question4 = State()
    question5 = State()
    question6 = State()
    question7 = State()
    question8 = State()
    answer = State()
    estination = State()
    last = State()
    pusto = State()
    kart_day = State()
    admin_stat = State()
    password = State()
    back_123 = State()
    select_stat = State()
