from handlers import main_menu
from handlers import where_are_you_able_to_answer
from handlers import backs
from handlers import decks
from handlers import cards_in_deck
from handlers import help_with_card_description
from handlers import estimate
from handlers import thems_and_answer_your_question
from handlers import deck_day
from handlers import admin_panel
